Use pytest for tests
metabrainz/listenbrainz-matching-tools pull request #11
Opened 2024-01-26 13:53 UTC by mayhem

Not much else to say...

2024-01-26 14:07 UTC, mayhem commented
I guess I do know what I am doing, lol. :)

2024-01-27 13:00 UTC, georgkrause requested changes

2024-01-27 13:00 UTC, georgkrause commented on tests/test_cleaner.py
> +        for testcase in ARTIST_TEST_STRINGS:
I think it would be better to use pytest parametrize feature instead of doing a loop manually: https://docs.pytest.org/en/7.3.x/how-to/parametrize.html

2024-01-27 13:00 UTC, georgkrause commented on .github/workflows/ci.yml
> +
Should I add reporting here?

2024-01-29 11:55 UTC, mayhem commented on .github/workflows/ci.yml
> +
Please!

2024-01-29 11:55 UTC, mayhem commented on tests/test_cleaner.py
> +        for testcase in ARTIST_TEST_STRINGS:
Good suggestion, done.

2024-01-30 15:51 UTC, georgkrause approved these changes

2024-01-30 15:51 UTC, merged